//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-CRUD-SSD_SERVICE_ID_sd_Y6j6UQEdljWUi5rG
import { CRUD as SSD_SERVICE_ID_sd_Y6j6UQEdljWUi5rG } from './sd-services/api/CRUD';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-CRUD-SSD_SERVICE_ID_sd_Y6j6UQEdljWUi5rG
SSD_SERVICE_ID_sd_Y6j6UQEdljWUi5rG,
];
